package com.bypriyan.bustrackingsystem.utility


object Constants{
    const val KEY_RESPONCE_SUCCESS= "success"
    const val KEY_RESPONCE_FAILED= "failed"
    //permission
    const val KEY_ADD_LEAD = "add-lead"
    const val KEY_EDIT_LEAD = "edit-lead"
    const val KEY_DELETE_LEAD = "delete-lead"
    const val KEY_VIEW_LEAD = "view-lead"
    const val KEY_CHANGE_STATUS_LEAD = "change-status-lead"
    const val KEY_CHANGE_STAGE_LEAD = "change-stage-lead"
    const val KEY_ASSIGN_LEAD = "assign-lead"
    const val KEY_BULK_LEAD_IMPORT = "bulk-lead-import"
    const val KEY_MANUAL_ASSIGN_LEAD = "manual-assign-lead"
    const val KEY_LEAD_DASHBOARD = "lead-dashboard"
    const val KEY_ADD_TASK = "add-task"
    const val KEY_EDIT_TASK = "edit-task"
    const val KEY_DELETE_TASK = "delete-task"
    const val KEY_VIEW_TASK = "view-task"
    const val KEY_ADD_REMAINDER = "add-remainder"
    const val KEY_EDIT_REMAINDER = "edit-remainder"
    const val KEY_DELETE_REMAINDER = "delete-remainder"
    const val KEY_VIEW_REMAINDER = "view-remainder"
    const val KEY_MAIN_DASHBOARD = "main-dashboard"
    const val KEY_ADD_DISTRIBUTE_COINS = "add-distriute-coins"
    const val KEY_UPLOAD_ACCOUNT = "upload-account"
    const val KEY_VIEW_ACCOUNT = "view-account"
    const val KEY_ADD_CAMPAIGN = "add-campaign"
    const val KEY_VIEW_CAMPAIGN = "view-campaign"
    const val KEY_EDIT_CAMPAIGN = "edit-campaign"
    const val KEY_DELETE_CAMPAIGN = "delete-campaign"
    const val KEY_CAMPAIGN_DASHBOARD = "campaign-dashboard"
    const val KEY_ADD_DEPARTMENT = "add-department"
    const val KEY_EDIT_DEPARTMENT = "edit-department"
    const val KEY_DELETE_DEPARTMENT = "delete-department"
    const val KEY_VIEW_DEPARTMENT = "view-department"
    const val KEY_ADD_DESIGNATION = "add-designation"
    const val KEY_EDIT_DESIGNATION = "edit-designation"
    const val KEY_DELETE_DESIGNATION = "delete-designation"
    const val KEY_VIEW_DESIGNATION = "view-designation"
    const val KEY_ADD_EMPLOYEE = "add-employee"
    const val KEY_EDIT_EMPLOYEE = "edit-employee"
    const val KEY_DELETE_EMPLOYEE = "delete-employee"
    const val KEY_VIEW_EMPLOYEE = "view-employee"
    const val KEY_ADD_PROJECT = "add-project"
    const val KEY_EDIT_PROJECT = "edit-project"
    const val KEY_DELETE_PROJECT = "delete-project"
    const val KEY_VIEW_PROJECT = "view-project"
    const val KEY_PROJECT_DETAILS = "project-details"

}